---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: release
  image: livingdocs/semantic-release:v2.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 1638372b4d7efb468c967330010ea7fc4ea50ecfc6bfd244715a6dd8c0bbc216

...
